// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlvptkwrehuoxvgwiurh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsdnB0a3dyZWh1b3h2Z3dpdXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMDM0NzYsImV4cCI6MjA4NzY3OTQ3Nn0.UEyVg26FHXIxckEesTuZ-meYb7pARsGEMBOEjmlFOxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});